[package]
name = "restmote-control-rs"
version = "0.1.0"
authors = ["Wilson Giese <giese.wilson@gmail.com>"]

[dependencies]
core-graphics = { git = "https://github.com/WilsonGiese/core-graphics-rs" }
getopts = "0.2.14"
libc = "0.2"
